<?php

global $lang;

$lang['en_US']['SilverChimp'] = array(
	'APIKEY'			=> 'MailChimp API Key',
	'LISTLABEL'	    => 'Select the list you wish to use',
    'SUBSCRIBESUCCESS' => 'Enter something to display when a subscription has been sucessful',
    'SETTINGSNOTE'    => 'You must save your changes to display/update the Chimp Fields tab',
    'FIELDSINTRO'     => 'These fields have been generated by Mail Chimp and will be used in your subscription form',

    'ADDRESS1'        => 'Street Address',
    'ADDRESS2'        => 'Address Line 2',
    'ADDRESS3'        => 'City',
    'ADDRESS4'        => 'State/Province/Region',
    'ADDRESS5'        => 'Postal/Zip Code',
    'COUNTRY'         => 'Country',
);

